openapi: '3.0.2'
info:
  title: Schema Files
  version: '1.0'
paths:
  /example:
    get:
      responses:
        '200':
          description: OK
components:
  schemas:
    ContactModel:
      type: object
      properties:
        id:
          type: string
        contact:
          $ref: '#/components/schemas/NameModel'
        address:
          $ref: '#/components/schemas/AddressModel'
    NameModel:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
    AddressModel:
      type: object
      properties:
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string

        



